name: tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  test:
    name: failing unit tests
    runs-on: ubuntu-latest
    steps:
      - run: true
